require File.dirname(__FILE__) + '/test_dependencies'

namespace :test do
  desc "Runs all unit tests"
  Rake::TestTask.new("units") do |t|
    t.pattern = '*_test.rb'
    t.verbose = true
    # t.warning = true
  end  
end
